# Generated by Django 3.0.7 on 2020-06-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=250)),
                ('image', models.ImageField(upload_to='project_images')),
            ],
        ),
    ]
